currency:
  available:
    - "RUB"
cost:
  rub:
    perKg: 427.18
    perKubM: 4233.57
    minimal: 350

boundary-coordinates:
  latitude-min-value:  45.0
  latitude-max-value:  65.0
  longitude-min-value:  30.0
  longitude-max-value:  96.0